services:
  app:
    build: .
    volumes:
      - ./data/:/data/
    environment:
        - PYTHONUNBUFFERED=no_buffer
        - PYTHONDONTWRITEBYTECODE=1
        - NVIDIA_VISIBLE_DEVICES=all
        - NVIDIA_DRIVER_CAPABILITIES=all
    runtime: nvidia
    privileged: true
    shm_size: '14gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    ipc: host
    ulimits:
      stack: 67108864
      memlock: -1
    ports:
      - "8000:8000"
